// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         string
	Name       string
	KeyHash    string
	CreatedBy  pgtype.Text
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	IsActive   bool
}

type Job struct {
	ID           string
	Type         string
	Payload      []byte
	Status       string
	Attempts     int32
	MaxAttempts  int32
	ErrorMessage pgtype.Text
	ScheduledAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
