// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbgen

import (
	"context"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (task, max_attempts) VALUES ($1, $2) RETURNING id, task, status, attempts, max_attempts, created_at, updated_at
`

type CreateJobParams struct {
	Task        string
	MaxAttempts int32
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.Task, arg.MaxAttempts)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failOrRetry = `-- name: FailOrRetry :one
UPDATE jobs
SET attempts = attempts + 1,
    status = CASE WHEN attempts + 1 >= max_attempts THEN 'failed' ELSE 'pending' END,
    updated_at = now()
WHERE id = $1
RETURNING id, task, status, attempts, max_attempts, created_at, updated_at
`

func (q *Queries) FailOrRetry(ctx context.Context, id int32) (Job, error) {
	row := q.db.QueryRow(ctx, failOrRetry, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingJobs = `-- name: GetPendingJobs :many
SELECT id, task, status, attempts, max_attempts, created_at, updated_at FROM jobs WHERE status = 'pending' ORDER BY created_at LIMIT $1
`

func (q *Queries) GetPendingJobs(ctx context.Context, limit int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, getPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDone = `-- name: MarkDone :exec
UPDATE jobs SET status = 'done', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkDone(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markDone, id)
	return err
}

const markProcessing = `-- name: MarkProcessing :one
UPDATE jobs SET status = 'processing', updated_at = now() WHERE id = $1 RETURNING id, task, status, attempts, max_attempts, created_at, updated_at
`

func (q *Queries) MarkProcessing(ctx context.Context, id int32) (Job, error) {
	row := q.db.QueryRow(ctx, markProcessing, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Task,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
